server:
  port: 8080
  servlet:
#   配置根路径
    context-path: /secondskill
spring:
  #  springboot热部署配置
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  profiles:
    active: zbw

mybatis:
  mapperLocations: classpath:mapping/*.xml

