server:
  port: 8090
  tomcat:
    #等待队列长度
    accept-count: 1000
    #最大工作线程数
    max-threads: 400
    #最小工作线程数
    min-spare-threads: 1000
    servlet:
      #配置根路径
      context-path: /secondskill
spring:
  #  springboot热部署配置
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    active: pro


mybatis:
  mapperLocations: classpath:mapping/*.xml



