spring:
  datasource:
    name: secondskill
    url: jdbc:mysql://114.55.218.127:3306/secondskill?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: WDTKzbw_njupt2020!
#   配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 10
    host: 172.16.215.158
    password: wdtk3366999.
    port: 6379
    jedis:
      pool:
        max-active: 50
        min-idle: 20