package com.zbw.secondskill.dao;

import com.zbw.secondskill.model.dataobject.ItemDo;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    ItemDo selectByPrimaryKey(Integer id);

    /**
     * @Param []
     * @Return List<ItemDo>
     * @Description 获取商品列表
     * @Author zbw
     * @Time 2020/3/1 12:55
     */
    List<ItemDo> listItem();

    /**
     * @Param [Integer id, Integer amount]
     * @Return int
     * @Description 增加订单销量
     * @Author zbw
     * @Time 2020/3/1 20:18
     */
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int updateByPrimaryKey(ItemDo record);
}