package com.zbw.secondskill.dao;

import com.zbw.secondskill.model.dataobject.ItemStockDo;
import io.lettuce.core.dynamic.annotation.Param;

public interface ItemStockDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int insert(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int insertSelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    ItemStockDo selectByPrimaryKey(Integer id);

    /**
     * @Param [Integer itemId)]
     * @Return com.zbw.secondskill.model.dataobject.ItemStockDo
     * @Description 根据itemId查询库存
     * @Author zbw
     * @Time 2020/3/1 15:04
     */
    ItemStockDo selectByItemId(Integer itemId);

    /**
     * @Param [Integer itemId, Integer amount]
     * @Return int
     * @Description 减库存操作
     * @Author zbw
     * @Time 2020/3/1 15:04
     */
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat Feb 29 22:47:45 GMT+08:00 2020
     */
    int updateByPrimaryKey(ItemStockDo record);
}