package com.zbw.secondskill.dao;

import com.zbw.secondskill.model.dataobject.SequenceDO;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 01 18:35:27 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 01 18:35:27 GMT+08:00 2020
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 01 18:35:27 GMT+08:00 2020
     */
    int insertSelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 01 18:35:27 GMT+08:00 2020
     */
    SequenceDO selectByPrimaryKey(String name);

    /**
     * @Param [String name]
     * @Return com.zbw.secondskill.model.datatobject.SequenceDO
     * @Description
     * @Author zbw
     * @Time 2020/3/1 18:41
     */
    SequenceDO getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 01 18:35:27 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Sun Mar 01 18:35:27 GMT+08:00 2020
     */
    int updateByPrimaryKey(SequenceDO record);
}