package com.zbw.secondskill.dao;

import com.zbw.secondskill.model.dataobject.UserPasswordDo;

public interface UserPasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int insert(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int insertSelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    UserPasswordDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int updateByPrimaryKey(UserPasswordDo record);

    /**
     * @Param id
     * @Return UserPasswordDo
     * @Description 根据用户id查找对应的UserPasswordDo
     * @Author zbw
     * @Time 2020/2/27 22:53
     */
    UserPasswordDo selectByUserId(Integer id);
}