package com.zbw.secondskill.dao;

import com.zbw.secondskill.model.dataobject.UserDo;

public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int insert(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int insertSelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    UserDo selectByPrimaryKey(Integer id);

    UserDo selectByTelephone(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Feb 27 21:34:26 GMT+08:00 2020
     */
    int updateByPrimaryKey(UserDo record);
}